### ISSUE TITLE
lo runie y...

### ISSUE THREAD

**Issue by Mapeadoh** [WarriorCrystal/CheatBreakerPlus-Issues#17]
se me puso un loro en la pantalla
un mono morado
la webcam estaba prendida y yo no la prendi
no me deja acceder a mis cuentas
no me anda el mc premium
quize formatear la pc y el disco duro esta corrompido
hay 54 carpetas llamadas "warrior crystal owns u" en modo oculto en la carpeta Windows

si no me dejas developear este cliente sos gei

**Comment by WarriorCrystal** [comment]
para q lo tenga luscius al dia siguiente?
