### ISSUE TITLE
GodModule (entity predict)

### ISSUE THREAD

**Issue by venuzhvh** [WarriorCrystal/CheatBreakerPlus-Issues#4]
add phobos 1.9.0 entity predict that predict the entity id to break it faster, also add crystal modifier from phobos to have a nice render :p

**Comment by WarriorCrystal** [comment]
si hablas español medio que no seas tan maricon de hacermela en ingles al pedo gordo pelotudo

**Comment by notperry1234567890** [comment]
> add phobos 1.9.0 entity predict that predict the entity id to break it faster, also add crystal modifier from phobos to have a nice render :p

this is in the new ca i gave to warrior in dms

**Comment by notperry1234567890** [comment]
it has break predict built in

**Comment by WarriorCrystal** [comment]
ok so
