### ISSUE TITLE
Finish LiquidInteract.

### ISSUE THREAD

**Issue by notperry1234567890** [WarriorCrystal/CheatBreakerPlus-Issues#6]
Another Incomplete module in b11 i saw when decompiling.

**Comment by WarriorCrystal** [comment]
i think i already added it on like b10 tell me if im wrong

**Comment by notperry1234567890** [comment]
idk i just decompiled it and i see that its empty

**Comment by WarriorCrystal** [comment]
it's because it works with mixins
