### ISSUE TITLE
Auto City

### ISSUE THREAD

**Issue by zIrsk** [WarriorCrystal/CheatBreakerPlus-Issues#7]

**Comment by WarriorCrystal** [comment]
que chota es obsi braker

**Comment by WarriorCrystal** [comment]
me voy a pensar en meter esto por ahora no lo tengo planeado para la b11.1

**Comment by notperry1234567890** [comment]
> _No description provided._

imagine not being able to manually city please quit.

**Comment by WarriorCrystal** [comment]
finished
